name: Optimize APK (dex -> STORED)
on: workflow_dispatch: {}
permissions: contents: write
jobs:
  optimize-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Instalar dependencias
      run: sudo apt-get update && sudo apt-get install -y zip unzip jq curl openjdk-11-jdk-headless openssl
    - name: Descargar APK
      env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        owner_repo="manpiro12/manpiro12"
        api_url="https://api.github.com/repos/$owner_repo/releases/latest"
        release_json=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$api_url")
        asset_api_url=$(echo "$release_json" | jq -r '.assets[] | select(.name | endswith(".apk")) | .url' | head -n1)
        if [ -z "$asset_api_url" ] || [ "$asset_api_url" = "null" ]; then echo "No .apk asset"; exit 1; fi
        curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/octet-stream" "$asset_api_url" -o original.apk
    - name: Extraer y reempaquetar con .dex STORED
      run: |
        rm -rf unpack || true; mkdir unpack; unzip -q original.apk -d unpack; rm -rf unpack/META-INF || true
        find . -type f -name "*.dex" -exec echo {} \; > dex_list.txt || true
        zip -r ../unsigned.apk unpack -x "unpack/**/*.dex" >/dev/null
        while read -r d; do zip -0 ../unsigned.apk "$d" >/dev/null; done < dex_list.txt || true
    - name: Instalar herramientas Android
      run: |
        export ANDROID_SDK_ROOT="$HOME/android-sdk"; mkdir -p $ANDROID_SDK_ROOT/cmdline-tools; cd $HOME
        curl -sSf -o cmdline-tools.zip "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip"
        unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest || true
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "build-tools;33.0.2" >/dev/null
    - name: Firmar APK
      run: |
        KS_PASS=$(openssl rand -base64 12)
        keytool -genkeypair -keystore release_keystore.jks -alias mykey -keyalg RSA -keysize 2048 -validity 10000 -storepass "$KS_PASS" -keypass "$KS_PASS" -dname "CN=manpiro12"
        if command -v zipalign >/dev/null; then zipalign -v -p 4 unsigned.apk unsigned-aligned.apk; else mv unsigned.apk unsigned-aligned.apk; fi
        apksigner sign --ks release_keystore.jks --ks-pass env:KS_PASS --key-pass env:KS_PASS --out optimized.apk unsigned-aligned.apk || (jarsigner -keystore release_keystore.jks -storepass "$KS_PASS" -keypass "$KS_PASS" unsigned-aligned.apk mykey && mv unsigned-aligned.apk optimized.apk)
    - name: Subir release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const tag = 'optimized-' + Date.now();
          const rel = await github.rest.repos.createRelease({ owner: context.repo.owner, repo: context.repo.repo, tag_name: tag, name: tag, body: 'APK optimizada' });
          const data = fs.readFileSync('optimized.apk');
          await github.rest.repos.uploadReleaseAsset({ owner: context.repo.owner, repo: context.repo.repo, release_id: rel.data.id, name: 'optimized.apk', data: data, headers: { 'content-type':'application/vnd.android.package-archive','content-length':data.length } });
